[Cias30-3490] DEV ==> HFHS-integration (#40)
* Add copyright and license noticies (#1182)

* fix some cases which test gem for fetching metadata

* [CIAS30-3372] documentation (#1184)

* [Cias30-3380] contributing guidelines and code of conduct (#1191)

* remove brakemn (#1192)

* [CIAS30-3321] add collaborators table (#1185)

* [CIAS30-3370] returns information about collaborators (#1186)

* [CIAS30-3333] new endpoints to handle sharing intervention (#1188)

* We should ignore roles: participant, organization admin, HC admin, HS admin (#1189)

* [CIAS30-3332] Add new rules to policy (#1194)

* [Cias30-3329] send mail when someone shares intervention with you (#1196)

* [CIAS30-3370] return information about collaborators (#1186)

* [CIAS30-3333] new endpoints to handle sharing intervention (#1188)

* [CIAS30-3332] add new rules to policy (#1194)

* [CIAS30-3330] send notifications (#1197)

* return collaborating_users_ids attr instead of collaborators in references, add collaborators to includes to avoid N+1 problem (#1204)

* change one behavior -> give permission to display collaborators not in his own interventions to super admin (#1210)

* expand #detailed_search to filter also by collaborating filters(shared with me, shared by me, not shared). Fix problem with interventions cache by adding 'touch: true' to collaborator's model (#1209)

* [CIAS30-3395] notify user when someone removes him/her from collaborators (#1208)

* [CIAS30-3410] add uniquess on relationship between intervention and user (collaborators) (#1207)

* replaced deprecating command - set-output (#11)

* replaced deprecating command - set-output, following https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

* small modification, recording to https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files

* [CIAS30-3387] add information about selected timezone and preferable time ranges into CSV (#14)

* add additional information to CSV (information about timezone and selected time ranges

* remove unnecesssary comments

* when sb fetchs all visible for him researcher shouldn't see himself on this list (#18)

* [CIAS30-3415] adjust endpoint to clone to accept emails instead of user_ids (#8)

* [CIAS30-3344/3343/3347/3349/3350] channel for colaboration (#6)

* [CIAS30-3343] add current collaborator to intervention (#1200)

* [CIAS30-3347/3347/3350] new actions in channel (start/stop editing) (#1203)

* [CIAS30-3347] new actions - force editing actions (#1205)

* Cias30 3413 update returned data format (#1211)

* Change data format returned in intervention channelz

* [CIAS30-3399] block not editor to update intervention (#7)

* [CIAS30-3422][CIAS30-3420] too many notifications after leaving the channel + Editing is not stopped on channel unsubscribe (#12)

* [CIAS-3341] -  Regenerate audio (#19)

* [CIAS-3341] - Regenerate audio

* [CIAS-3341] - Make rubocop happy

* [CIAS-3341] - Make rubocop happy

* [CIAS-3341] - Small fixes

* [CIAS-3341] - Make rubocop happy

* [CIAS-3341] - Code review changes

* [CIAS-3341] - Code review changes

* [CIAS-3341] - Rubocop fixes

* add default values to settings in the number question (#9)

* add new values to settings in number questions - max and min length (#10)

* [CIAS30-3421] script to fetch researchers (#15)

* [CIAS30-3438] removed protected attachments from the intervention's serializer (#20)

* added missing rules to e-int admin's ability(among others: fetch report templates, sms-es, sessions) (#21)

* allow to add a super admin to collaborators (#22)

* block super admin possibility to grant data access for not his/her intervention, small cleanup (#23)

* [CIAS30-3458] a researcher couldn't remove questions (#24)

* fix problem with remove questions, mave this check to 'ability_to_update_for?' method

* undid unnecessary changes

* removed unued endpoints with their services

* remove removed endpoints from routes.rb and one test

* [CIAS-3419] - Add simple intervention serializer (#27)

* [CIAS30-3461] new endpoint to fetch permission for the collaborator (#28)

* removed 'currentUserCollaboratorData' because of cache. Add new endpoint to fetch removed date

* put correct description to the test

* adjust the test to current code

* allow all with intervention access to connect to the InterventionChannel (#31)

* [CIAS-3419] - Fix cache key (#30)

* [CIAS-3419] - Fix cache key

* [CIAS-3419] - Make rubocop happy

* [Cias30-3417] restructure csv (#33)

* add one for for session with 'multiple_fill' option

* all sessions in intervention should be in one row

* upgrade rails 6.1.7.3 to 6.1.7.4

* added authorization to header_names and that solved the issue with 'NoMethodError (undefined method 'downcase' for nil:NilClass):

rack (2.2.6.4) lib/rack/utils.rb:476:in '[]='

* allow to pass emails instead of ids (#34)

* clear cache during the next deploy (#35)

* Update README.md by Steve (#36)

* Update README.md by Steve

Slight modifications to description of features and access model. Identical to changes made on cias-web.

* Fix duplicated paragraph

---------

Co-authored-by: bartosz-kepka-htd <bartosz.kepka@htdevelopers.com>

* [CIAS30-3486] Update repo links in documentation (#37)

* adjust new approach to generate CSV -> include HFHS data

---------

Co-authored-by: msniecHTD <115976801+msniecHTD@users.noreply.github.com>
Co-authored-by: onders12 <81652438+onders12@users.noreply.github.com>
Co-authored-by: bartosz-kepka-htd <bartosz.kepka@htdevelopers.com>
Co-authored-by: Bartosz Kępka <86963976+bartosz-kepka-htd@users.noreply.github.com>