[Cias30-3154] verify participant in epic (#3)
* [CIAS30-3279] raise exception if user wants to fill scheduled session (#1143)

* check if last session is finished before mark this user intervetnion as completed

* add test

* [CIAS30-3256] add no_formula_image to sms_plan (#1147)

* [Cias30-3255] add images to variants in smses (#1148)

* [CIAS30-3257] Include images when sensing messages via Twilio (#1151)

* fix image url in Communication::SMS service

* [CIAS30-3297] add new fields to session model (#1152)

* [CIAS-3267] add new flag and update existing questions (#1155)

* [CIAS-3267] make job activation dependent on question settings in the session (#1156)

* change minutes to hours (#1157)

* block option to send welcome emails for guest and preview users (#1158)

* add start autofinish timer to new question (#1160)

* block possibility to modify question if intervention is published (#1161)

* start_autofinish_timer for question finish settings (#1163)

* [CIAS30-3249] time ranges (#1162)

* [CIAS30-3250] apply randomization during sending sms-es (#1164)

* [CIAS30-3337] add timezone (#1165)

* [CIAS30-3292] add users to the allowed list when the researcher sends an invitation via email to them  (#1167)

* [CIAS30-3362] change letters in emails to lowercase (#1170)

* [CIAS30-3355] reset timeout job (#1172)

* happy path: get access token

* gem for moc requests|

* update nokogiri from 1.13.10 to 1.14.3

* restore missing method (#1173)

* [CIAS30-3328] [CIAS30-3339] change image to attachment for sms and sms_variant (#1166)

* [CIAS30-3367] change format of returned attachment in sms_plan_ and variant_serializer (#1176)

* fix sharing/coping (#1177)

* remove unued lib

* remove unused requirement

* make rubocop blind

* add envs from EPIC to our template

* WIP

* add new exceptions and take care of edge cases

* add missing lib

* rubocop -A

* Add copyright and license noticies (#1182)

* fix some cases which test gem for fetching metadata

* [CIAS30-3372] documentation (#1184)

* resolve issue with  WebMock::NetConnectNotAllowedError

* [Cias30-3380] contributing guidelines and code of conduct (#1191)

* remove brakemn (#1192)

* [CIAS30-3321] add collaborators table (#1185)

* [CIAS30-3370] returns information about collaborators (#1186)

* [CIAS30-3333] new endpoints to handle sharing intervention (#1188)

* We should ignore roles: participant, organization admin, HC admin, HS admin (#1189)

* [CIAS30-3332] Add new rules to policy (#1194)

* [Cias30-3329] send mail when someone shares intervention with you (#1196)

* [CIAS30-3370] return information about collaborators (#1186)

* [CIAS30-3333] new endpoints to handle sharing intervention (#1188)

* [CIAS30-3332] add new rules to policy (#1194)

* [CIAS30-3330] send notifications (#1197)

* return collaborating_users_ids attr instead of collaborators in references, add collaborators to includes to avoid N+1 problem (#1204)

* change one behavior -> give permission to display collaborators not in his own interventions to super admin (#1210)

* expand #detailed_search to filter also by collaborating filters(shared with me, shared by me, not shared). Fix problem with interventions cache by adding 'touch: true' to collaborator's model (#1209)

* [CIAS30-3395] notify user when someone removes him/her from collaborators (#1208)

* [CIAS30-3410] add uniquess on relationship between intervention and user (collaborators) (#1207)

* replaced deprecating command - set-output (#11)

* replaced deprecating command - set-output, following https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

* small modification, recording to https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files

* [CIAS30-3387] add information about selected timezone and preferable time ranges into CSV (#14)

* add additional information to CSV (information about timezone and selected time ranges

* remove unnecesssary comments

* when sb fetchs all visible for him researcher shouldn't see himself on this list (#18)

* [CIAS30-3415] adjust endpoint to clone to accept emails instead of user_ids (#8)

* [CIAS30-3344/3343/3347/3349/3350] channel for colaboration (#6)

* [CIAS30-3343] add current collaborator to intervention (#1200)

* [CIAS30-3347/3347/3350] new actions in channel (start/stop editing) (#1203)

* [CIAS30-3347] new actions - force editing actions (#1205)

* Cias30 3413 update returned data format (#1211)

* Change data format returned in intervention channelz

* [CIAS30-3399] block not editor to update intervention (#7)

* [CIAS30-3422][CIAS30-3420] too many notifications after leaving the channel + Editing is not stopped on channel unsubscribe (#12)

* [CIAS-3341] -  Regenerate audio (#19)

* [CIAS-3341] - Regenerate audio

* [CIAS-3341] - Make rubocop happy

* [CIAS-3341] - Make rubocop happy

* [CIAS-3341] - Small fixes

* [CIAS-3341] - Make rubocop happy

* [CIAS-3341] - Code review changes

* [CIAS-3341] - Code review changes

* [CIAS-3341] - Rubocop fixes

* add default values to settings in the number question (#9)

* add new values to settings in number questions - max and min length (#10)

* [CIAS30-3421] script to fetch researchers (#15)

* [CIAS30-3438] removed protected attachments from the intervention's serializer (#20)

* added missing rules to e-int admin's ability(among others: fetch report templates, sms-es, sessions) (#21)

* allow to add a super admin to collaborators (#22)

* block super admin possibility to grant data access for not his/her intervention, small cleanup (#23)

* [CIAS30-3458] a researcher couldn't remove questions (#24)

* fix problem with remove questions, mave this check to 'ability_to_update_for?' method

* undid unnecessary changes

* removed unued endpoints with their services

* remove removed endpoints from routes.rb and one test

* [CIAS-3419] - Add simple intervention serializer (#27)

* [CIAS30-3461] new endpoint to fetch permission for the collaborator (#28)

* removed 'currentUserCollaboratorData' because of cache. Add new endpoint to fetch removed date

* put correct description to the test

* adjust the test to current code

* allow all with intervention access to connect to the InterventionChannel (#31)

* [CIAS-3419] - Fix cache key (#30)

* [CIAS-3419] - Fix cache key

* [CIAS-3419] - Make rubocop happy

* [Cias30-3417] restructure csv (#33)

* add one for for session with 'multiple_fill' option

* all sessions in intervention should be in one row

* upgrade rails 6.1.7.3 to 6.1.7.4

* added authorization to header_names and that solved the issue with 'NoMethodError (undefined method 'downcase' for nil:NilClass):

rack (2.2.6.4) lib/rack/utils.rb:476:in '[]='

* allow to pass emails instead of ids (#34)

* clear cache during the next deploy (#35)

* fix issue with the path

* remove binding

* [CIAS30-3373] fetch appointments from epic (#4)

* service to get appointments

* modify verification of patient and gathering needed information: visit_id and patient_id

* Update README.md by Steve (#36)

* Update README.md by Steve

Slight modifications to description of features and access model. Identical to changes made on cias-web.

* Fix duplicated paragraph

---------

Co-authored-by: bartosz-kepka-htd <bartosz.kepka@htdevelopers.com>

* -add required parameters to henry-ford-details
-add phone number and type to serializer;
- removed unused copy
- adapt V1::HenryFord::VerifyService

* fix bug in serializer

* small refactor

* add new exceptions to handler

* fix issue reported by bundler-audit

* add env to env.template

* WIP

* small adjustments add soem tests

* removed doorkeeper and endpoint to create hfhs_patient_details

* make rubocop happy:

* small fix

* Update config/locales/en.yml

Co-authored-by: msniecHTD <115976801+msniecHTD@users.noreply.github.com>

* WebMock.allow_net_connect

* [CIAS30-3486] Update repo links in documentation (#37)

* add missing key to expected array in index spec for jwk-set

* fix tests

* generate an example private and public keys for CI purpose

* update env.template

* add new columns to our CSV (#38)

* fix corse file

* add logs

* fix bug

* fix tests on GH

* removed unneeded part of the code (#39)

* fix error with fetching appointments

* restored missing method

* restored missing methods

* [Cias30-3490] DEV ==> HFHS-integration (#40)

* Add copyright and license noticies (#1182)

* fix some cases which test gem for fetching metadata

* [CIAS30-3372] documentation (#1184)

* [Cias30-3380] contributing guidelines and code of conduct (#1191)

* remove brakemn (#1192)

* [CIAS30-3321] add collaborators table (#1185)

* [CIAS30-3370] returns information about collaborators (#1186)

* [CIAS30-3333] new endpoints to handle sharing intervention (#1188)

* We should ignore roles: participant, organization admin, HC admin, HS admin (#1189)

* [CIAS30-3332] Add new rules to policy (#1194)

* [Cias30-3329] send mail when someone shares intervention with you (#1196)

* [CIAS30-3370] return information about collaborators (#1186)

* [CIAS30-3333] new endpoints to handle sharing intervention (#1188)

* [CIAS30-3332] add new rules to policy (#1194)

* [CIAS30-3330] send notifications (#1197)

* return collaborating_users_ids attr instead of collaborators in references, add collaborators to includes to avoid N+1 problem (#1204)

* change one behavior -> give permission to display collaborators not in his own interventions to super admin (#1210)

* expand #detailed_search to filter also by collaborating filters(shared with me, shared by me, not shared). Fix problem with interventions cache by adding 'touch: true' to collaborator's model (#1209)

* [CIAS30-3395] notify user when someone removes him/her from collaborators (#1208)

* [CIAS30-3410] add uniquess on relationship between intervention and user (collaborators) (#1207)

* replaced deprecating command - set-output (#11)

* replaced deprecating command - set-output, following https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

* small modification, recording to https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files

* [CIAS30-3387] add information about selected timezone and preferable time ranges into CSV (#14)

* add additional information to CSV (information about timezone and selected time ranges

* remove unnecesssary comments

* when sb fetchs all visible for him researcher shouldn't see himself on this list (#18)

* [CIAS30-3415] adjust endpoint to clone to accept emails instead of user_ids (#8)

* [CIAS30-3344/3343/3347/3349/3350] channel for colaboration (#6)

* [CIAS30-3343] add current collaborator to intervention (#1200)

* [CIAS30-3347/3347/3350] new actions in channel (start/stop editing) (#1203)

* [CIAS30-3347] new actions - force editing actions (#1205)

* Cias30 3413 update returned data format (#1211)

* Change data format returned in intervention channelz

* [CIAS30-3399] block not editor to update intervention (#7)

* [CIAS30-3422][CIAS30-3420] too many notifications after leaving the channel + Editing is not stopped on channel unsubscribe (#12)

* [CIAS-3341] -  Regenerate audio (#19)

* [CIAS-3341] - Regenerate audio

* [CIAS-3341] - Make rubocop happy

* [CIAS-3341] - Make rubocop happy

* [CIAS-3341] - Small fixes

* [CIAS-3341] - Make rubocop happy

* [CIAS-3341] - Code review changes

* [CIAS-3341] - Code review changes

* [CIAS-3341] - Rubocop fixes

* add default values to settings in the number question (#9)

* add new values to settings in number questions - max and min length (#10)

* [CIAS30-3421] script to fetch researchers (#15)

* [CIAS30-3438] removed protected attachments from the intervention's serializer (#20)

* added missing rules to e-int admin's ability(among others: fetch report templates, sms-es, sessions) (#21)

* allow to add a super admin to collaborators (#22)

* block super admin possibility to grant data access for not his/her intervention, small cleanup (#23)

* [CIAS30-3458] a researcher couldn't remove questions (#24)

* fix problem with remove questions, mave this check to 'ability_to_update_for?' method

* undid unnecessary changes

* removed unued endpoints with their services

* remove removed endpoints from routes.rb and one test

* [CIAS-3419] - Add simple intervention serializer (#27)

* [CIAS30-3461] new endpoint to fetch permission for the collaborator (#28)

* removed 'currentUserCollaboratorData' because of cache. Add new endpoint to fetch removed date

* put correct description to the test

* adjust the test to current code

* allow all with intervention access to connect to the InterventionChannel (#31)

* [CIAS-3419] - Fix cache key (#30)

* [CIAS-3419] - Fix cache key

* [CIAS-3419] - Make rubocop happy

* [Cias30-3417] restructure csv (#33)

* add one for for session with 'multiple_fill' option

* all sessions in intervention should be in one row

* upgrade rails 6.1.7.3 to 6.1.7.4

* added authorization to header_names and that solved the issue with 'NoMethodError (undefined method 'downcase' for nil:NilClass):

rack (2.2.6.4) lib/rack/utils.rb:476:in '[]='

* allow to pass emails instead of ids (#34)

* clear cache during the next deploy (#35)

* Update README.md by Steve (#36)

* Update README.md by Steve

Slight modifications to description of features and access model. Identical to changes made on cias-web.

* Fix duplicated paragraph

---------

Co-authored-by: bartosz-kepka-htd <bartosz.kepka@htdevelopers.com>

* [CIAS30-3486] Update repo links in documentation (#37)

* adjust new approach to generate CSV -> include HFHS data

---------

Co-authored-by: msniecHTD <115976801+msniecHTD@users.noreply.github.com>
Co-authored-by: onders12 <81652438+onders12@users.noreply.github.com>
Co-authored-by: bartosz-kepka-htd <bartosz.kepka@htdevelopers.com>
Co-authored-by: Bartosz Kępka <86963976+bartosz-kepka-htd@users.noreply.github.com>

* fix tests

* updated some gems

* [Cias30-3502] Return hfhs_patient_detail when fetching question in user session (#49)

* [CIAS30-3466] (#29)

* before create access-tokens we will check to things: if T&C are accepted and 2FA needed and return related errors

* [CIAS-3388] - Add terms verification

* [CIAS-3388] - Fix actionpack

* [CIAS-3388] - Fix gemfile

* [CIAS-3388] - Cr changes

* [CIAS-3388] - Revert lock changes

* [CIAS-3388] - Make rubocop happy

* [CIAS-3388] - Revert rubocop changes

* [CIAS-3388] - Cr changes

* [CIAS-3388] - Fix test

---------

Co-authored-by: msniecHTD <michal.sniec@htdevelopers.com>

* [CIAS30-3417] fix for error while generating CSV (#43)

* fix for the edge case: when the researcher changed the multiple_fill session during testing

* updated some gems - needed for security reason

* customize error message (#42)

* [CIAS30-3492] "Share Externally" modal is not case sensitive (#41)

* use #downcase to successfuly search users by email

* restore db

* WIP

* WIP

* [CIAS30-3505] add info about first and last name (#48)

* added tests + removed  from

* removed comments

* fixed tests

* added locations to our db,models and relationship between intervention and locations, added needed endpoint and modified existing one(update for intervention)

* added locations to seeds

* fixed error

* modify a litte bit tests

* remove hfhs details from expected response when we fetching users

* remove outdate part of the tests

* removed outdate code

* small adjustments + logic to select visit_id

* small adjustmens and add test to cover on case

* for demo

* WebMock.disable

* fixed tests

---------

Co-authored-by: msniecHTD <michal.sniec@htdevelopers.com>
Co-authored-by: OskarDybowski <138489528+OskarDybowski@users.noreply.github.com>

---------

Co-authored-by: msniecHTD <115976801+msniecHTD@users.noreply.github.com>
Co-authored-by: onders12 <81652438+onders12@users.noreply.github.com>
Co-authored-by: bartosz-kepka-htd <bartosz.kepka@htdevelopers.com>
Co-authored-by: Bartosz Kępka <86963976+bartosz-kepka-htd@users.noreply.github.com>
Co-authored-by: msniecHTD <michal.sniec@htdevelopers.com>
Co-authored-by: OskarDybowski <138489528+OskarDybowski@users.noreply.github.com>